#!/bin/sh


 
echo " ██████╗ ███████╗██████╗ ██╗    ██╗███╗   ███╗██████╗ ██╗   ██╗██████╗  █████╗ ██████╗  ██████╗██╗  ██╗      ██████╗ ███████╗██████╗ ██╗ █████╗ ███╗   ██╗  ";
echo " ██╔══██╗██╔════╝██╔══██╗██║    ██║████╗ ████║██╔══██╗╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗██╔════╝██║  ██║      ██╔══██╗██╔════╝██╔══██╗██║██╔══██╗████╗  ██║  ";
echo " ██████╔╝███████╗██████╔╝██║ █╗ ██║██╔████╔██║██████╔╝ ╚████╔╝ ██║  ██║███████║██████╔╝██║     ███████║█████╗██║  ██║█████╗  ██████╔╝██║███████║██╔██╗ ██║  ";
echo " ██╔══██╗╚════██║██╔═══╝ ██║███╗██║██║╚██╔╝██║██╔══██╗  ╚██╔╝  ██║  ██║██╔══██║██╔══██╗██║     ██╔══██║╚════╝██║  ██║██╔══╝  ██╔══██╗██║██╔══██║██║╚██╗██║  ";
echo " ██████╔╝███████║██║     ╚███╔███╔╝██║ ╚═╝ ██║██████╔╝   ██║   ██████╔╝██║  ██║██║  ██║╚██████╗██║  ██║      ██████╔╝███████╗██████╔╝██║██║  ██║██║ ╚████║  ";
echo " ╚═════╝ ╚══════╝╚═╝      ╚══╝╚══╝ ╚═╝     ╚═╝╚═════╝    ╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝      ╚═════╝ ╚══════╝╚═════╝ ╚═╝╚═╝  ╚═╝╚═╝  ╚═══╝  ";
                                                                                                                                                                                                                                                                     
sleep 3

sudo -v
while true; do
  sudo -nv; sleep 1m
  kill -0 $$ 2>/dev/null || exit
done &

#sudo apt install sudo y mandarlo con sed e usuario a sudoers
#instalar xorg xbackight
#Instalar bspwmbydarch
cd 
sudo apt install bspwm sxhkd xdg-user-dirs cmake make git curl wget 
xdg-user-dirs-update
git clone https://github.com/darch7/bspwmbydarch-debian
cp -R bspwmbydarch-debian/config/* $HOME/.config/ 
cp -R bspwmbydarch-debian/.local $HOME/ 
sudo chmod +x .local/bin/scripts
cp -R bspwmbydarch-debian/home/.[^.]* $HOME/ 
cd bspwmbydarch-debian/compilar/st 
sudo make install 
cd 
sudo cp -R bspwmbydarch-debian/root/gtk/iconos/* /usr/share/icons
sudo cp -R bspwmbydarch-debian/root/gtk/temas/* /usr/share/themes
sudo cp -R bspwmbydarch-debian/root/wall/* /usr/share/

neofetch
sleep 5
uname -r 
sleep 3

echo "BspwmbyDarch instalado"
sleep 5
clear
reboot
